services:
  front:
    build: ./frontend/app-front
    ports:
      - "${EXT_FRONT_PORT}:${INT_FRONT_PORT}"
    volumes:
      - ./frontend/app-front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  back:
    build: ./backend
    ports:
      - "${EXT_BACK_PORT}:${INT_BACK_PORT}"
    volumes:
      - ./backend:/code
