services:
  front:
    build: 
      context: .
      dockerfile: frontend/app-front/Dockerfile
    env_file: .env
    ports:
      - "${EXT_FRONT_PORT}:${INT_FRONT_PORT}"
    volumes:
      - ./frontend/app-front:/front
      - /front/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  back:
    build: ./backend
    depends_on:
      - db
    ports:
      - "${EXT_BACK_PORT}:${INT_BACK_PORT}"
    environment:
      DB_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_PORT: ${INT_DB_PORT}
    volumes:
      - ./backend:/code

  db:
    build: ./db
    ports:
      - "${EXT_DB_PORT}:${INT_DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_mysql:/var/lib/mysql

  test-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: flixy_test
    ports:
      - "3307:3306"

volumes:
  db_mysql:
