services:
  front:
    build: ./frontend/app-front
    ports:
      - "${EXT_FRONT_PORT}:${INT_FRONT_PORT}"
    volumes:
      - ./frontend/app-front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  back:
    build: ./backend
    ports:
      - "${EXT_BACK_PORT}:${INT_BACK_PORT}"
    volumes:
      - ./backend:/code

  db:
    build: ./db
    ports:
      - "${EXT_DB_PORT}:${INT_DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_mysql:/var/lib/mysql
  
volumes:
  db_mysql:
