name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1] # Uses 1 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend/app-front

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend/app-front

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # Starts web server for E2E tests
          start: npm start
          wait-on: "http://localhost:3000"
          # Records to Cypress Cloud
          record: true
          parallel: true # Runs test in parallel using settings above
          working-directory: ./frontend/app-front
        env:
          CYPRESS_FRONT_URL: http://localhost:3000
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
