name: Cypress Tests
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: flixy
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Wait for DB
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..20}; do
            mysqladmin ping -h 127.0.0.1 -P 3306 -uroot -proot >/dev/null 2>&1 && break
            echo "Waiting..."
            sleep 3
          done

      - name: Load database schema
        run: |
          mysql -h 127.0.0.1 -P 3306 -uroot -proot flixy < ./db/schema_structure.sql

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Start backend
        run: |
          export DB_USER=root
          export DB_PWD=root
          export DB_HOST=127.0.0.1
          export DBE_PORT=3306
          uvicorn backend.main:app --host 0.0.0.0 --port 8000 &
          echo "Waiting for backend to be ready..."
          npx wait-on http://127.0.0.1:8000/docs

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend/app-front

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend/app-front

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: "http://localhost:3000 http://127.0.0.1:8000/docs"
          wait-on-timeout: 180
          record: true
          parallel: false
        working-directory: ./frontend/app-front
        env:
          VITE_API_URL: http://127.0.0.1:8000
          VITE_API_URL_CLIENT: http://localhost:8000
          CYPRESS_FRONT_URL: http://localhost:3000
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
