name: Run backend tests

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      test-db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: flixy_test
        ports:
          - 3306:3306
        options: >-
          --name test-db
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub to avoid rate limits
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL..."
          sleep 20

      - name: Run tests
        working-directory: ./backend
        env:
          TEST_DATABASE_URL: mysql+mysqlconnector://root:root@127.0.0.1:3306/flixy_test
          AI_API_KEY: ${{ secrets.MODERATOR_API_KEY }}
        run: pytest

  deploy-api:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main' }}
    steps:
      - name: Call webhook depending on branch
        run: |
          if [ "${GITHUB_REF##*/}" = "dev" ]; then
            curl "${{ secrets.WEBHOOK_URL_DEV }}"
          elif [ "${GITHUB_REF##*/}" = "main" ]; then
            curl "${{ secrets.WEBHOOK_URL_MAIN }}"
          fi
